# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile


tasks:
  - name: Terminal
    before: echo 'the before terminal' 
    init: echo 'initial script' # runs during prebuild
    command: echo 'start script'
  
  - name: Terminal 2
    init: echo 'the after terminal 1'
    command: zsh
  #- name: skipmvnTest
  #  init: ./mvnw clean install -DskipTests=true

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-lombok
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - felipecaputo.git-project-manager
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - evondev.indent-rainbow-palettes
    - donjayamanne.git-extension-pack
    - esbenp.prettier-vscode
    - redhat.vscode-xml
    - rangav.vscode-thunder-client
    - developersoapbox.vscode-springboot-developer-pack
    - ms-azuretools.vscode-dapr
    - bierner.markdown-preview-github-styles
    - oderwat.indent-rainbow
    - cweijan.git-graph-history
    - mhutchie.git-graph
    - ms-vscode.makefile-tools
    - mongodb.mongodb-vscode 
