# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.dockerfile


tasks:
  - name: Terminal
    before: echo 'the before terminal' 
    init: echo 'initial script' # runs during prebuild
    command: echo 'start script'
  
  - name: Terminal 2
    init: echo 'the after terminal 1'
    command: zsh

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
