# Start All services
services:
    # MySQL service
    mysql:
        image: mysql:8.3.0 # mysql image
        container_name: mysql # image name
        ports:  # define port
            - "3306:3306" # port value
        environment: # define environmental  values
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql/data:/var/lib/mysql
    # start Mongo service
    mongo:
        image: mongo:7.0.5
        container_name: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: product-service
        volumes:
            - ./docker/mongodb/data:/data/db
