server:
    port: 7000

logging:
    level:
        web: DEBUG

# configs
#Resilinece4j Properties
resilience4j:
    circuitbreaker:
        instances:
            example:
                registerHealthIndicator: true
                event-consumer-buffer-size: 10
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 5s
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true

    #Resilience4J Timeout Properties
    #resilience4j:
    timelimiter:
        instances:
            example:
                timeout-duration: 3s

    #Resilience4J Retry Properties
    retry:
        instances:
            example:
                max-attempts: 3
                wait-duration: 5s